name: nao_controller
description: Nao Controller App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/

  uses-material-design: true